
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  base_url: !secret hassio_url
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Xiaomi
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

# InfluxDB for grafana
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# System monitor
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent 
      - type: memory_use 
      - type: memory_free 
      - type: swap_use_percent 
      - type: swap_use 
      - type: swap_free 
      - type: load_1m 
      - type: load_5m 
      - type: load_15m 
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
      - type: packets_in
        arg: eth0
      - type: packets_out
        arg: eth0
      - type: ipv4_address
        arg: eth0
      - type: processor_use 
      - type: last_boot
  - platform: apcupsd
    resources:
      - apc
      - date
      - version
      - upsname
      - cable
      - driver
      - upsmode
      - starttime
      - model
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - mbattchg
      - mintimel
      - maxtime
      - maxlinev
      - minlinev
      - outputv

# APC
apcupsd:
  host: a722577e-apcupsd

# Xbox
media_player:
  - platform: xboxone
    device: !secret xbox_device_id
    name: Xbox One

